astraceroute-libs =	-lGeoIP \
			-lpthread \
			-lz

astraceroute-objs =	xmalloc.o \
			ioops.o \
			xutils.o \
			proto_none.o \
			tprintf.o \
			bpf.o \
			str.o \
			sig.o \
			sock.o \
			link.o \
			dev.o \
			geoip.o \
			ring_rx.o \
			ring.o \
			astraceroute.o
