astraceroute-libs =	-lGeoIP \
			-lpthread

astraceroute-objs =	xmalloc.o \
			xio.o \
			xutils.o \
			proto_none.o \
			tprintf.o \
			aslookup.o \
			bpf.o \
			mtrand.o \
			ring_rx.o \
			astraceroute.o
