=head1 NAME

astraceroute - autonomous system (AS) trace route utility

=head1 SYNOPSIS

  astraceroute [-Hpi46nNfmqxSAFPUREtGXZlwWvh]
    [-H|--host <host>]     [-p|--port <port>]
    [-i|-d|--dev <dev>]           [-4|--ipv4]
    [-6|--ipv6]                [-n|--numeric]
    [-N|--dns]          [-f|--init-ttl <ttl>]
    [-m|--max-ttl <ttl>]    [-q|--num-probes]
    [-x|--timeout <sec>]           [-S|--syn]
    [-A|--ack]                     [-F|--fin]
    [-P|--psh]                     [-U|--urg]
    [-R|--rst]                 [-E|--ecn-syn]
    [-t|--tos <tos>]            [-G|--nofrag]
    [-X|--payload <string>][-Z|--show-packet]
    [-l|--totlen <len>] [-w|--whois <server>]
    [-W|--wport <port>]    [--city-db <path>]
    [--country-db <path>]      [-v|--version]
    [-h|--help]
  astraceroute6 [options]

=head1 DESCRIPTION

astraceroute provides traceroute-like AS and estimated geographical information
on each hop between the client and the targeted host. Unlike L<traceroute(1)>,
it uses TCP-based packets (e.g. a TCP-SYN packet for opening a new connection)
in order to prevent being filtered by firewalls. It automatically falls back to
ICMP-based probes in case a timeout occurred after no answer was received and
the probe times threshold was exceeded. Also, unlike L<tcptraceroute(1)>, the
packet flags are fully customizable and AS information such as the AS number of
the hop as well as country code, country and city are provided with estimated
longitude and latitude. Furthermore, astraceroute provides the reverse DNS name
of the hop, its IP address, the network prefix of the AS, the registry name of
the AS, a registered since of the AS and the human readable AS name.

=head1 EXAMPLES

=over

=item astraceroute -i eth0 -N -E -H netsniff-ng.org

IPv4 trace of AS with TCP ECN SYN probe

=item astraceroute -i eth0 -N -S -H netsniff-ng.org

IPv4 trace of AS with TCP SYN probe

=item astraceroute -i eth0 -N -F -H netsniff-ng.org

IPv4 trace of AS with TCP FIN probe

=item astraceroute -i eth0 -N -FPU -H netsniff-ng.org

IPv4 trace of AS with Xmas probe

=item astraceroute -i eth0 -N -H netsniff-ng.org -X "censor-me" -Z

IPv4 trace of AS with Null probe with ASCII payload

=item astraceroute -6 -S -i eth0 -H netsniff-ng.org

IPv6 trace of AS up to netsniff-ng.org

=back

=head1 OPTIONS

=over

=item -h|--help

Print help text and lists all options.

=item -v|--version

Print version.

=item -H|--host <host>

Host/IPv4/IPv6 to lookup AS route to

=item i-|-d|--dev <netdev>

Networking device, i.e. eth0

=item -p|--port <port>

Hosts port to lookup AS route to

=item -4|--ipv4

Use IPv4 requests (default)

=item -6|--ipv6

Use IPv6 requests

=item -n|--numeric

Do not do reverse DNS lookup for hops

=item -N|--dns

Do a reverse DNS lookup for hops

=item -f|--init-ttl <ttl>

Set initial TTL

=item -m|--max-ttl <ttl>

Set maximum TTL (default: 30)

=item -q|--num-probes <num>

Number of max probes for each hop (default: 3)

=item -x|--timeout <sec>

Probe response timeout in sec (default: 3)

=item -S|--syn

Set TCP SYN flag in packets

=item -A|--ack

Set TCP ACK flag in packets

=item -F|--fin

Set TCP FIN flag in packets

=item -P|--psh

Set TCP PSH flag in packets

=item -U|--urg

Set TCP URG flag in packets

=item -R|--rst

Set TCP RST flag in packets

=item -E|--ecn-syn

Send ECN SYN packets (RFC3168)

=item -t|--tos <tos>

Set the IP TOS field

=item -w|--whois <server>

Use a different AS whois DB server
(default: /etc/netsniff-ng/whois.conf)

=item -W|--wport <port>

Use a different port to AS whois server
(default: /etc/netsniff-ng/whois.conf)

=item --city-db <path>

Specifiy path for geoip city database

=item --country-db <path>

Specifiy path for geoip country database

=back

=head1 AVAILABILITY

astraceroute is part of the netsniff-ng toolkit. More information about the
toolkit can be obtained from its website: http://netsniff-ng.org/

=head1 GIT

All source code is available under the terms of the GNU GPL, version 2.0.
Obtain it via Git from: git://github.com/gnumaniacs/netsniff-ng.git

=head1 AUTHOR

astraceroute was written by Daniel Borkmann <daniel@netsniff-ng.org>.

=head1 DOCUMENTATION

The documentation was written by Emmanuel Roullit <emmanuel@netsniff-ng.org>
and Daniel Borkmann <daniel@netsniff-ng.org>.

=head1 BUGS

Please report bugs to <bugs@netsniff-ng.org>.

=head1 SEE ALSO

L<traceroute(1)>, L<tcptraceroute(1)>, L<ping(8)>

=cut
