=head1 NAME

bpfc - compile a BPF expression into BPF opcode

=head1 SYNOPSIS

bpfc -i|--input <program> [-V|--verbose][-v|--version][-h|--help]

=head1 DESCRIPTION

bpfc is a tool to generate BPF opcode from a literal expression.
The generated BPF opcode then can be used to filter out the
corresponding traffic.

=head1 EXAMPLES

=over

=item bpfc --input example.bpf

Transform the literal expression in example.bpf into BPF opcodes

=back

=head1 OPTIONS

=over

=item -i|--input <program>

Path to Berkeley Packet Filter file.

=item -V|--verbose

Increase program verbosity

=item -v|--version

Print version.

=item -h|--help

Print help text and lists all options.

=back

=head1 AUTHOR

Written by Daniel Borkmann <daniel@netsniff-ng.org>

=head1 DOCUMENTATION

Documentation by Emmanuel Roullit <emmanuel@netsniff-ng.org>

=head1 BUGS

Please report bugs to <bugs@netsniff-ng.org>

=cut
