=head1 NAME

curvetun - lightweight curve25519-based multiuser IP tunnel

=head1 SYNOPSIS

curvetun [-d|--dev <tun>][-x|--export][-C|--dumpc][-S|--dumps]
[-k|--keygen][-c|--client [<alias>]][-s|--server][-N|--no-logging]
[-p|--port <num>][-t|--stun <server>][-4|--ipv4][-6|--ipv6]
[-v|--version][-h|--help]

=head1 DESCRIPTION

curvetun embeds a client and a server to build and manage multiuser
IP tunnels using Elliptic Curve Cryptography (ECC)

=head1 EXAMPLES

=over

=item curvetun --keygen

Generate public/private keypair. This needs to be done before
to get things started.

=item curvetun --export

Export public data to remote servers

=item curvetun --server -4 -u -N --port 6666 --stun stunserver.org

Start a UDP IPv4 curvetun server on port 6666.
Use stunserver.org as STUN server.

=item curvetun --client=ethz

Start curvetun client using the profile called 'ethz'

=back

=head1 OPTIONS

=over

=item -k|--keygen

Generate public/private keypair.

=item -x|--export

Export your public data for remote servers.

=item -C|--dumpc

Dump parsed clients.

=item -S|--dumps

Dump parsed servers.

=item -D|--nofork

Do not daemonize.

=item -d|--dev <tun>

Networking tunnel device, e.g. tun0.

=item -c|--client [<alias>]

Client mode, server alias optional.

=item -s|--server

Server mode.

=item -N|--no-logging

Disable server logging (for better anonymity).

=item -p|--port <num>

Port number (mandatory).

=item -t|--stun <server>

Show public IP/Port mapping via STUN.

=item -u|--udp

Use UDP as carrier instead of TCP.

=item -4|--ipv4

Tunnel devices are IPv4.

=item -6|--ipv6

Tunnel devices are IPv6.

=item -v|--version

Print version.

=item -h|--help

Print help text and lists all options.

=back

=head1 AUTHOR

Written by Daniel Borkmann <daniel@netsniff-ng.org> and Emmanuel Roullit <emmanuel@netsniff-ng.org>

=head1 DOCUMENTATION

Documentation by Emmanuel Roullit <emmanuel@netsniff-ng.org>

=head1 BUGS

Please report bugs to <bugs@netsniff-ng.org>

=cut
