curvetun-libs =	-lnacl.a \
		-lpthread

curvetun-objs =	xmalloc.o \
		xio.o \
		xutils.o \
		stun.o \
		mtrand.o \
		patricia.o \
		trie.o \
		hash.o \
		curve.o \
		ct_cpusched.o \
		ct_usermgmt.o \
		ct_servmgmt.o \
		ct_server.o \
		ct_client.o \
		curvetun.o
