flowtop-libs =	-lGeoIP \
		-lurcu \
		-lnetfilter_conntrack \
		-lncurses \
		-lpthread

flowtop-objs =	xmalloc.o \
		xio.o \
		xutils.o \
		oui.o \
		hash.o \
		dissector_eth.o \
		dissector_80211.o \
		dissector.o \
		proto_none.o \
		tprintf.o \
		flowtop.o
