#!/bin/sh

#
# netsniff-ng Project
# Code indention script
#

files=`find $1 -type f | egrep "*.c$|*.h$"`

echo "Indenting `echo $files | wc -w` files (`cat $files | wc -l` lines) ..."

for file in $files
do
        indent -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce   \
               -ci4 -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l120 -lp -npcs -nprs  \
               -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8  \
               -il1 $file
done
