netsniff-ng-libs =	-lpthread \
			-lnl-genl-3

netsniff-ng-objs =	hash.o \
			mac80211.o \
			dissector.o \
			dissector_eth.o \
			dissector_80211.o \
			proto_arp.o \
			proto_ethernet.o \
			proto_icmpv4.o \
			proto_icmpv6.o \
			proto_igmp.o \
			proto_ip_authentication_hdr.o \
			proto_ip_esp.o \
			proto_ipv4.o \
			proto_ipv6.o \
			proto_ipv6_dest_opts.o \
			proto_ipv6_fragm.o \
			proto_ipv6_hop_by_hop.o \
			proto_ipv6_in_ipv4.o \
			proto_ipv6_mobility_hdr.o \
			proto_ipv6_no_nxt_hdr.o \
			proto_ipv6_routing.o \
			proto_none.o \
			proto_tcp.o \
			proto_udp.o \
			proto_vlan.o \
			proto_vlan_q_in_q.o \
			proto_mpls_unicast.o \
			proto_80211_mac_hdr.o \
			xio.o \
			xutils.o \
			xmalloc.o \
			bpf.o \
			oui.o \
			pcap.o \
			pcap_rw.o \
			pcap_sg.o \
			pcap_mmap.o \
			ring_rx.o \
			ring_tx.o \
			mtrand.o \
			tprintf.o \
			netsniff-ng.o
