trafgen-libs =	-lnl-genl-3 \
		-lnl-3 \
		-lm

trafgen-objs =	xmalloc.o \
		xio.o \
		xutils.o \
		mac80211.o \
		ring_tx.o \
		trafgen_lexer.yy.o \
		trafgen_parser.tab.o \
		trafgen.o

trafgen-lex =	trafgen_lexer.yy.o

trafgen-yaac =	trafgen_parser.tab.o
