bpfc-libs =

bpfc-objs =	xmalloc.o \
		xutils.o \
		bpf.o \
		bpf_symtab.o \
		bpfc/bpf_lexer.yy.o \
		bpfc/bpf_parser.tab.o \
		bpfc/bpf_hla_lexer.yy.o \
		bpfc/bpf_hla_parser.tab.o \
		bpfc.o

bpfc-lex =	bpf_lexer.yy.o \
		bpf_hla_lexer.yy.o

bpfc-yaac =	bpf_parser.tab.o \
		bpf_hla_parser.tab.o
