curvetun-libs =	-lnacl \
		-lpthread

curvetun-objs =	xmalloc.o \
		xio.o \
		xutils.o \
		str.o \
		stun.o \
		patricia.o \
		corking.o \
		trie.o \
		hash.o \
		rnd.o \
		curve.o \
		cpusched.o \
		ct_usermgmt.o \
		ct_servmgmt.o \
		ct_server.o \
		ct_client.o \
		curvetun.o
