curvetun-libs =	-lnacl \
		-lpthread

curvetun-objs =	xmalloc.o \
		epoll2.o \
		str.o \
		dev.o \
		stun.o \
		sock.o \
		sig.o \
		link.o \
		patricia.o \
		corking.o \
		trie.o \
		taia.o \
		hash.o \
		rnd.o \
		curve.o \
		cookie.o \
		keypair.o \
		ioexact.o \
		ioops.o \
		cpusched.o \
		ct_usermgmt.o \
		ct_servmgmt.o \
		ct_server.o \
		ct_client.o \
		curvetun.o
