.\" 
.\" netsniff-ng.man
.\" 
.\" netsniff-ng, a high performance network sniffer for packet inspection
.\" 
.\" Copyright 2009 by Daniel Borkmann
.\" 
.\" License: GPL, version 2
.\" 
.TH "netsniff-ng" "8" "December 2009" "Leipzig University of Applied Sciences" "User Manuals"
.SH "NAME"
netsniff\-ng \- a high performance network sniffer for packet inspection
.SH "SYNOPSIS"
.B netsniff\-ng [\-d 
.I device
.B ] [\-f
.I filter
.B ]
.B [\-C] ...
.SH "DESCRIPTION"
.B netsniff\-ng 
is a high performance linux network sniffer for packet inspection. Basically, it is similar to tcpdump, but it doesn't need a syscall per packet. Instead, it uses an memory mapped area within kernelspace for accessing packets without copying them to userspace (zero\-copy mechanism), so during high bandwidth less packet drops than on libpcap\-based sniffers will occur.

.br 
.br 
netsniff\-ng is useful for debugging your network, measuring performance throughput or creating network statistics of incoming packets on central network nodes like routers or firewalls.

.br 
.br 
By providing a unix domain socket client (\fBcheck_packets\fR), you are able to export the collected data during runtime (e.g. for Nagios). 
.SH "OPTIONS"
.IP "\fB\-d\fR \fIdevice\fR"
For instance, use `eth0' or `wlan0' as the packet capturing network device.

.IP "\fB\-f\fR \fIfilter\fR"
Use a specific \fIBerkeley Packet Filter\fR program to filter incoming packets. 
.br 
Have a look at the given examples in: 
.I /etc/netsniff\-ng/rules

.IP "\fB\-C\fR"
Print captured packets to stdout.

.IP "\fB\-D\fR"
Run netsniff\-ng in daemon mode, options \fB\-P\fR, \fB\-L\fR and \fB\-S\fR are required, too. 
.br 
Note: To gather statistics during runtime without the unix domain socket inode, just send \fBSIGUSR1\fR to netsniff\-ng.

.IP "\fB\-P\fR \fIpidfile\fR"
Used to define the pidfile. In most cases you can define it as \fI/var/run/netsniff\-ng.pid\fR.

.IP "\fB\-L\fR \fIlogfile\fR"
Used to define the logfile. In most cases you can define it as \fI/var/log/netsniff\-ng.log\fR.

.IP "\fB\-S\fR \fIinode\fR"
Used to define the unix domain socket inode. In most cases you can define it as \fI/tmp/netsniff\-ng.uds\fR.
.SH "AUTHOR"
(C) 2009, by Daniel Borkmann
.br 

For bug reports, questions, code contributions and all the rest:
.br 
.br 

.IP ""
\fI<dborkman@fbimn.htwk\-leipzig.de>\fR, or
.IP ""
\fI<dborkmann@acm.org>\fR
