ifpps-libs =	$(shell pkg-config --libs ncurses)

ifpps-objs =	xmalloc.o \
		ioops.o \
		str.o \
		link.o \
		sock.o \
		dev.o \
		sig.o \
		screen.o \
		ifpps.o

ifpps-eflags = $(shell pkg-config --cflags ncurses)

ifpps-confs =
