trafgen-libs =	-lnl-genl-3

trafgen-objs =	xmalloc.o \
		xio.o \
		xutils.o \
		mtrand.o \
		mac80211.o \
		ring_tx.o \
		trafgen/trafgen_lexer.yy.o \
		trafgen/trafgen_parser.tab.o \
		trafgen.o

trafgen-lex =	trafgen_lexer.yy.o

trafgen-yaac =	trafgen_parser.tab.o
